const scene=document.querySelector('#curtainScene');const enter=document.querySelector('#enterButton');const menu=document.querySelector('#menuButton');const nav=document.querySelector('#nav');
const openCurtain=()=>{scene.classList.add('open');document.body.classList.remove('curtain-locked');localStorage.setItem('velvetEntered','yes')};
enter.addEventListener('click',openCurtain);
if(localStorage.getItem('velvetEntered')==='yes'){scene.remove();document.body.classList.remove('curtain-locked')}
menu.addEventListener('click',()=>{const isOpen=nav.classList.toggle('open');menu.setAttribute('aria-expanded',String(isOpen))});
nav.querySelectorAll('a').forEach(link=>link.addEventListener('click',()=>{nav.classList.remove('open');menu.setAttribute('aria-expanded','false')}));
const experiences={restore:{number:'01',title:'The Velvet Reset',copy:'A flowing, full-body ritual created to settle your nervous system, soften overworked muscles, and make room for a deeper exhale.',best:'Stress • fatigue • whole-body renewal'},release:{number:'02',title:'The Deep Release',copy:'Focused therapeutic care for the places that work hardest. Pressure and technique are adjusted to meet your body without overpowering it.',best:'Tight shoulders • back tension • active bodies'},ground:{number:'03',title:'The Grounding Ritual',copy:'Slow, intentional bodywork designed to quiet mental noise, restore balance, and help you feel fully present in your body again.',best:'Overstimulation • emotional fatigue • reset'},glow:{number:'04',title:'The Renewal Experience',copy:'An uplifting ritual that encourages circulation, restores ease, and leaves you feeling lighter from the inside out.',best:'Sluggish energy • special occasions • fresh starts'}};
const card=document.querySelector('#experienceCard');document.querySelectorAll('.feeling-tab').forEach(tab=>tab.addEventListener('click',()=>{document.querySelectorAll('.feeling-tab').forEach(t=>{t.classList.remove('active');t.setAttribute('aria-selected','false')});tab.classList.add('active');tab.setAttribute('aria-selected','true');const x=experiences[tab.dataset.feeling];card.animate([{opacity:.35,transform:'translateY(8px)'},{opacity:1,transform:'none'}],{duration:350});card.querySelector('.experience-number').textContent=x.number;card.querySelector('h3').textContent=x.title;card.querySelector('p').textContent=x.copy;card.querySelector('strong').textContent=x.best}));
const rooms={arrival:{kicker:'Begin here',title:'The Garden of Arrival',copy:'Greenery, florals, and quiet details create the first exhale. This is where the outside world begins to fall away.',services:['Welcome & check-in','Intentional arrival']},wisdom:{kicker:'Be seen & understood',title:'The Wisdom Chamber',copy:'A consultation space surrounded by cultural collections, credentials, and thoughtful refreshment—where your needs are heard before care begins.',services:['VIP consultation','Wellness planning','Refreshments']},celestial:{kicker:'Pause between worlds',title:'Celestial Velvet Lounge',copy:'A moonlit holding and relaxation room with velvet, crystals, and constellation details for quiet moments before and after treatment.',services:['Pre-treatment relaxation','Post-treatment integration','V.elevate member experience']},chakra:{kicker:'Restore the whole body',title:'Chakra Sanctuary',copy:'The main massage sanctuary blends skilled touch with chakra-centered calm, subtle garden energy, and celestial details.',services:['60-minute massage','Neuromuscular therapy','Swedish massage','Sports massage','Deep-tissue massage','Energy balancing','Sound therapy','CBD enhancements']},lotus:{kicker:'Care for every detail',title:'Lotus Ritual Suite',copy:'A floral, water-inspired suite for beauty, grounding, and focused hand-and-foot care.',services:['45-minute Foot Reflexology','Queen’s Manicure & Pedicure','Facial massage','Hand & foot rituals','Body treatments','Beauty add-ons']}};
const roomPanel=document.querySelector('#roomPanel');document.querySelectorAll('.room-tab').forEach(tab=>tab.addEventListener('click',()=>{document.querySelectorAll('.room-tab').forEach(t=>{t.classList.remove('active');t.setAttribute('aria-selected','false')});tab.classList.add('active');tab.setAttribute('aria-selected','true');const x=rooms[tab.dataset.room];roomPanel.animate([{opacity:.35,transform:'translateX(8px)'},{opacity:1,transform:'none'}],{duration:350});roomPanel.querySelector('.room-kicker').textContent=x.kicker;roomPanel.querySelector('h3').textContent=x.title;roomPanel.querySelector('p').textContent=x.copy;roomPanel.querySelector('.service-chips').innerHTML=x.services.map(service=>`<span>${service}</span>`).join('')}));
const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');observer.unobserve(entry.target)}}),{threshold:.14});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));
document.querySelector('#year').textContent=new Date().getFullYear();
