const scene=document.querySelector('#curtainScene');const enter=document.querySelector('#enterButton');const menu=document.querySelector('#menuButton');const nav=document.querySelector('#nav');
const openCurtain=()=>{scene.classList.add('open');document.body.classList.remove('curtain-locked');localStorage.setItem('velvetEntered','yes')};
enter.addEventListener('click',openCurtain);
if(localStorage.getItem('velvetEntered')==='yes'){scene.remove();document.body.classList.remove('curtain-locked')}
menu.addEventListener('click',()=>{const isOpen=nav.classList.toggle('open');menu.setAttribute('aria-expanded',String(isOpen))});
nav.querySelectorAll('a').forEach(link=>link.addEventListener('click',()=>{nav.classList.remove('open');menu.setAttribute('aria-expanded','false')}));
const experiences={restore:{number:'01',title:'The Velvet Reset',copy:'A flowing, full-body ritual created to settle your nervous system, soften overworked muscles, and make room for a deeper exhale.',best:'Stress • fatigue • whole-body renewal'},release:{number:'02',title:'The Deep Release',copy:'Focused therapeutic care for the places that work hardest. Pressure and technique are adjusted to meet your body without overpowering it.',best:'Tight shoulders • back tension • active bodies'},ground:{number:'03',title:'The Grounding Ritual',copy:'Slow, intentional bodywork designed to quiet mental noise, restore balance, and help you feel fully present in your body again.',best:'Overstimulation • emotional fatigue • reset'},glow:{number:'04',title:'The Renewal Experience',copy:'An uplifting ritual that encourages circulation, restores ease, and leaves you feeling lighter from the inside out.',best:'Sluggish energy • special occasions • fresh starts'}};
const card=document.querySelector('#experienceCard');document.querySelectorAll('.feeling-tab').forEach(tab=>tab.addEventListener('click',()=>{document.querySelectorAll('.feeling-tab').forEach(t=>{t.classList.remove('active');t.setAttribute('aria-selected','false')});tab.classList.add('active');tab.setAttribute('aria-selected','true');const x=experiences[tab.dataset.feeling];card.animate([{opacity:.35,transform:'translateY(8px)'},{opacity:1,transform:'none'}],{duration:350});card.querySelector('.experience-number').textContent=x.number;card.querySelector('h3').textContent=x.title;card.querySelector('p').textContent=x.copy;card.querySelector('strong').textContent=x.best}));
const square='https://book.squareup.com/appointments/u0wax21hze3dit/location/AHT2JGX482KPT/services/';
const rooms={
 arrival:{kicker:'Begin here',title:'The Garden of Arrival',copy:'Greenery, florals, and quiet details create the first exhale. This is where the outside world begins to fall away.',features:['Welcome & check-in','Intentional arrival'],services:[]},
 wisdom:{kicker:'Be seen & understood',title:'The Wisdom Chamber',copy:'A consultation space surrounded by cultural collections, credentials, and thoughtful refreshment—where your needs are heard before care begins.',features:['VIP consultation','Wellness planning','Membership guidance','Refreshments'],services:[]},
 celestial:{kicker:'Pause between worlds',title:'Celestial Velvet Lounge',copy:'A moonlit holding and relaxation room—and the center point for experiences that flow through more than one treatment space.',features:['Pre-treatment relaxation','Post-treatment integration','Whole-spa journeys'],services:[
  ['V.elevate Member Massage Experiences','Price varies • 30 min+','GPVC3VNVSIFKITWBOCO47ODZ'],
  ["Queen’s Retreat","$220 • 1 hr 30 min",'Q543VLA7A3U2RGV2S5QR534U','60-minute massage + Queen’s facial massage + reflexology'],
  ['VElevate CBD-Infused Spa Day','$284 • 1 hr 30 min','7PTNRBKRURY4JDR7PP2FFD7X','60-minute CBD massage + facial massage + detox reflexology soak'],
  ['Goddess Facial + Sound Therapy + Foot Treatment','$100 • 1 hr','HGQ2ZBFRWG2EHLBF2H4AQBLD'],
  ['Enchanting Enhancements','Price varies • 15 min+','JFDKLBY4PUOOWAARMQFDR7KD','Add-on upgrades for eligible experiences']
 ]},
 chakra:{kicker:'Restore the whole body',title:'Chakra Sanctuary',copy:'The main massage sanctuary blends skilled touch with chakra-centered calm, subtle garden energy, and celestial details.',features:['Massage therapy','Energy alignment','Sound therapy'],services:[
  ['Therapeutic Massage','$160 • 1 hr 30 min','IXSRA2CALXNE4TYGLWZXPSJX','Contact the spa before booking: massage care is temporarily limited to 60 minutes'],
  ['Neuromuscular Therapy','Price varies • 1 hr+','NQJ2D262B4FNZILZPIALGNQD','Trigger-point and neuromuscular techniques'],
  ['Chakra Alignment','$60 • 45 min','PEU265JDBLHWO7DI7RBATYJC','Chakra assessment + sound-bowl treatment']
 ]},
 lotus:{kicker:'Care for every detail',title:'Lotus Ritual Suite',copy:'A floral, water-inspired suite for beauty, grounding, and focused face, hand, and foot care.',features:['Facial massage','Reflexology','Nail & beauty rituals'],services:[
  ['Goddess Manicure & Pedicure','Price varies • 45 min+','7LLT3QI6FG3NWP4MLVDFANUL'],
  ['Facial Massage Menu','Price varies • 20 min+','N22P7RVDZU4YPUD7AIEZV2UC'],
  ['Paroah Facial Massage','$50 • 30 min','EZQVEZ66DQLQP75XSLUIO2PW','Men’s facial + scalp massage'],
  ["Pharoah’s Pedicure & Manicure",'$60 • 2 hr','GADLW2CGGPV2BHOTL6PPUWZC'],
  ['Reflexology','$60 • 30 min','OMHSLDUORLE4ILPS6KVBVT7C','30-minute foot massage'],
  ['Princess Manicure & Pedicure','Price varies • 25 min+','CHQJM3EBARC4RW7UVC6H32G6','Clean, shape, and polish'],
  ['Makeup Menu','Price varies • 20 min+','HDZS2DJKPC4ADYPRJRNL4N4D'],
  ['Intro to Wellness Reflexology Series','$285 • 1 hr 15 min','G74Z5MOIFVCAJFINATSZU73O','Series of 3 Goddess/Pharaoh pedicure + reflexology experiences'],
  ['Foot Reflexology','Price varies • 15 min+','BO3PXII5FRQCOHRAPE5YRR7L']
 ]}
};
const roomPanel=document.querySelector('#roomPanel');document.querySelectorAll('.room-tab').forEach(tab=>tab.addEventListener('click',()=>{document.querySelectorAll('.room-tab').forEach(t=>{t.classList.remove('active');t.setAttribute('aria-selected','false')});tab.classList.add('active');tab.setAttribute('aria-selected','true');const x=rooms[tab.dataset.room];roomPanel.animate([{opacity:.35,transform:'translateX(8px)'},{opacity:1,transform:'none'}],{duration:350});roomPanel.querySelector('.room-kicker').textContent=x.kicker;roomPanel.querySelector('h3').textContent=x.title;roomPanel.querySelector('p').textContent=x.copy;roomPanel.querySelector('.service-chips').innerHTML=x.features.map(feature=>`<span>${feature}</span>`).join('');roomPanel.querySelector('.room-services').innerHTML=x.services.length?x.services.map(service=>`<a class="service-card" href="${square+service[2]}"><strong>${service[0]}</strong><small>${service[1]}</small>${service[3]?`<em>${service[3]}</em>`:''}</a>`).join(''):'<p class="room-empty">This room prepares and supports your reserved experience rather than offering a separate bookable service.</p>'}));

const quizQuestions=[
 {q:'What do you need most today?',options:[['Deep relaxation','restore'],['Pain and tension relief','release'],['Emotional or energetic balance','ground'],['A refreshed, radiant feeling','glow']]},
 {q:'Where is your body asking for the most attention?',options:[['My full body','restore'],['Neck, shoulders, or back','release'],['Face, scalp, and skin','glow'],['Hands, feet, or lower legs','ground']]},
 {q:'What style of care feels best right now?',options:[['Gentle and soothing','restore'],['Focused and therapeutic','release'],['Energy and sound based','ground'],['Beauty and spa focused','glow']]},
 {q:'How much time would you like to make for yourself?',options:[['About 30 minutes','time30'],['About 45 minutes','time45'],['About 60 minutes','time60'],['A 75–90 minute journey','time90']]},
 {q:'Which sensory enhancement calls to you?',options:[['Aromatherapy','aroma'],['Sound bowls','sound'],['CBD body care','cbd'],['Keep it beautifully simple','simple']]},
 {q:'Would you enjoy a beauty or finishing ritual?',options:[['Facial massage','facial'],['Hand or foot care','feet'],['Makeup artistry','makeup'],['No beauty add-on today','none']]},
 {q:'How do you want wellness to fit into your life?',options:[['A one-time reset','once'],['A regular monthly ritual','monthly'],['I’m curious about V.Elevate','member'],['I’m preparing for an occasion','occasion']]},
 {q:'How do you want to feel when you leave?',options:[['Calm enough to float','restore'],['Loose, mobile, and relieved','release'],['Grounded and centered','ground'],['Radiant and renewed','glow']]}
];
const quizProfiles={
 restore:{name:'The Velvet Restoration Ritual',summary:'A deeply calming experience designed to quiet your nervous system, soften the whole body, and give you space to fully exhale.',base:['60-minute restorative massage','Intentional aromatherapy finish'],room:'Chakra Sanctuary',service:'IXSRA2CALXNE4TYGLWZXPSJX'},
 release:{name:'The Royal Release Ritual',summary:'Focused care designed around muscular tension, improved movement, and the areas of your body that have been working the hardest.',base:['Targeted neuromuscular bodywork','Focused tension-release plan'],room:'Chakra Sanctuary',service:'NQJ2D262B4FNZILZPIALGNQD'},
 ground:{name:'The Celestial Grounding Ritual',summary:'A centering experience that combines energy awareness, sound, and focused care to help you feel present in your body again.',base:['Chakra alignment','Sound-bowl integration'],room:'Chakra Sanctuary + Celestial Velvet Lounge',service:'PEU265JDBLHWO7DI7RBATYJC'},
 glow:{name:'The Goddess Glow Ritual',summary:'A restorative beauty experience for the face, scalp, hands, or feet that leaves you feeling polished, cared for, and renewed.',base:['Personalized facial massage','Aromatherapy beauty ritual'],room:'Lotus Ritual Suite',service:'N22P7RVDZU4YPUD7AIEZV2UC'}
};
let quizIndex=0;let quizAnswers=Array(quizQuestions.length).fill(null);
const quizStep=document.querySelector('#quizStep'),quizResult=document.querySelector('#quizResult'),quizQuestion=document.querySelector('#quizQuestion'),quizOptions=document.querySelector('#quizOptions'),quizCount=document.querySelector('#quizCount'),quizProgress=document.querySelector('#quizProgress'),quizBack=document.querySelector('#quizBack'),quizNext=document.querySelector('#quizNext');
function renderQuiz(){const item=quizQuestions[quizIndex];quizCount.textContent=`Question ${quizIndex+1} of ${quizQuestions.length}`;quizQuestion.textContent=item.q;quizProgress.style.width=`${((quizIndex+1)/quizQuestions.length)*100}%`;quizOptions.innerHTML=item.options.map((o,i)=>`<button class="quiz-option${quizAnswers[quizIndex]===o[1]?' selected':''}" type="button" data-value="${o[1]}">${o[0]}</button>`).join('');quizBack.disabled=quizIndex===0;quizNext.disabled=!quizAnswers[quizIndex];quizNext.textContent=quizIndex===quizQuestions.length-1?'Design my package':'Continue';quizOptions.querySelectorAll('.quiz-option').forEach(button=>button.addEventListener('click',()=>{quizAnswers[quizIndex]=button.dataset.value;quizOptions.querySelectorAll('.quiz-option').forEach(b=>b.classList.toggle('selected',b===button));quizNext.disabled=false}))}
function showQuizResult(){const scores={restore:0,release:0,ground:0,glow:0};quizAnswers.forEach(answer=>{if(scores[answer]!==undefined)scores[answer]++});const winner=Object.entries(scores).sort((a,b)=>b[1]-a[1])[0][0];const profile=quizProfiles[winner];const additions=[];if(quizAnswers.includes('aroma')&&!profile.base.some(x=>x.toLowerCase().includes('aroma')))additions.push('Aromatherapy enhancement');if(quizAnswers.includes('sound')&&!profile.base.some(x=>x.toLowerCase().includes('sound')))additions.push('Sound-bowl enhancement');if(quizAnswers.includes('cbd'))additions.push('CBD body-care enhancement');if(quizAnswers.includes('facial')&&!profile.base.some(x=>x.toLowerCase().includes('facial')))additions.push('Facial massage ritual');if(quizAnswers.includes('feet'))additions.push('Reflexology or hand-and-foot ritual');if(quizAnswers.includes('makeup'))additions.push('Makeup artistry finish');if(quizAnswers.includes('member'))additions.push('V.Elevate membership consultation');const journey=[...profile.base,...additions].slice(0,4);const timeAnswer=quizAnswers.find(a=>a&&a.startsWith('time'));const timeMap={time30:'30-minute focus',time45:'45-minute ritual',time60:'60-minute experience',time90:'75–90 minute spa journey'};document.querySelector('#resultName').textContent=profile.name;document.querySelector('#resultSummary').textContent=profile.summary;document.querySelector('#resultJourney').innerHTML=journey.map((x,i)=>`<div class="result-item"><span>0${i+1}</span><strong>${x}</strong></div>`).join('');document.querySelector('#resultTime').textContent=timeMap[timeAnswer]||'Personalized timing';document.querySelector('#resultRoom').textContent=profile.room;document.querySelector('#resultBook').href=square+profile.service;quizStep.hidden=true;quizResult.hidden=false;quizProgress.style.width='100%'}
quizNext.addEventListener('click',()=>{if(!quizAnswers[quizIndex])return;if(quizIndex<quizQuestions.length-1){quizIndex++;renderQuiz()}else showQuizResult()});quizBack.addEventListener('click',()=>{if(quizIndex>0){quizIndex--;renderQuiz()}});document.querySelector('#quizRestart').addEventListener('click',()=>{quizIndex=0;quizAnswers=Array(quizQuestions.length).fill(null);quizResult.hidden=true;quizStep.hidden=false;renderQuiz()});renderQuiz();
const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');observer.unobserve(entry.target)}}),{threshold:.14});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));
document.querySelector('#year').textContent=new Date().getFullYear();
