import React, { useEffect, useMemo, useState } from 'react';
import { Alert, Linking, Platform, Pressable, SafeAreaView, ScrollView, StatusBar, StyleSheet, Switch, Text, TextInput, View } from 'react-native';
import { LinearGradient } from 'expo-linear-gradient';
import * as SecureStore from 'expo-secure-store';
import * as Notifications from 'expo-notifications';
import { useFonts, CormorantGaramond_500Medium, CormorantGaramond_600SemiBold, CormorantGaramond_700Bold } from '@expo-google-fonts/cormorant-garamond';
import { Manrope_400Regular, Manrope_500Medium, Manrope_600SemiBold, Manrope_700Bold } from '@expo-google-fonts/manrope';

const C = { ink: '#100716', plum: '#2b0b3d', purple: '#6d2b85', gold: '#d8ae58', pale: '#f7efd9', white: '#fffdf8' };
const SQUARE = 'https://book.squareup.com/appointments/u0wax21hze3dit/location/AHT2JGX482KPT/services/';
const WEBSITE = 'https://www.velvetspaunlimited.com';
type Tab = 'home' | 'explore' | 'quiz' | 'velvet';
type Intake = { name: string; email: string; phone: string; goals: string; concerns: string };

const rooms = [
  { key: 'arrival', symbol: '✿', name: 'Garden of Arrival', tone: ['#163828', '#4d1c62'] as const, copy: 'A lush first exhale where greenery, florals, and intentional welcome soften the outside world.', details: ['Welcome and check-in', 'Personalized intake', 'Experience finder'] },
  { key: 'wisdom', symbol: '☥', name: 'Wisdom Chamber', tone: ['#2b1538', '#6d5126'] as const, copy: 'A private consultation space where your needs are heard before care begins.', details: ['Wellness planning', 'Membership guidance', 'Private consultation'] },
  { key: 'celestial', symbol: '☾', name: 'Celestial Velvet Lounge', tone: ['#151335', '#5b226d'] as const, copy: 'A moonlit pause for pre-treatment relaxation and post-treatment integration.', details: ['Quiet arrival', 'Whole-spa journeys', 'Post-care reflection'] },
  { key: 'chakra', symbol: '✧', name: 'Chakra Sanctuary', tone: ['#321044', '#183b37'] as const, copy: 'The heart of therapeutic bodywork, chakra-centered calm, and sound-supported restoration.', details: ['Massage therapy', 'Neuromuscular care', 'Energy alignment'] },
  { key: 'lotus', symbol: '♢', name: 'Lotus Renewal Suite', tone: ['#43143d', '#244b45'] as const, copy: 'A floral, water-inspired suite for reflexology, facial massage, and detailed renewal.', details: ['Facial massage', 'Reflexology', 'Hand and foot care'] },
];
const services = [
  { name: 'Therapeutic Massage', meta: '$160 • 90 minutes', id: 'IXSRA2CALXNE4TYGLWZXPSJX' },
  { name: 'Neuromuscular Therapy', meta: 'From 60 minutes', id: 'NQJ2D262B4FNZILZPIALGNQD' },
  { name: 'Chakra Alignment', meta: '$60 • 45 minutes', id: 'PEU265JDBLHWO7DI7RBATYJC' },
  { name: 'Queen’s Retreat', meta: '$220 • 90 minutes', id: 'Q543VLA7A3U2RGV2S5QR534U' },
  { name: 'Reflexology', meta: '$60 • 30 minutes', id: 'OMHSLDUORLE4ILPS6KVBVT7C' },
];
const questions = [
  ['What do you need most today?', [['Deep relaxation', 'restore'], ['Pain and tension relief', 'release'], ['Emotional or energetic balance', 'ground'], ['A refreshed, radiant feeling', 'glow']]],
  ['Where is your body asking for attention?', [['My full body', 'restore'], ['Neck, shoulders, or back', 'release'], ['Face, scalp, and skin', 'glow'], ['Hands, feet, or lower legs', 'ground']]],
  ['What style of care feels best?', [['Gentle and soothing', 'restore'], ['Focused and therapeutic', 'release'], ['Energy and sound based', 'ground'], ['Beauty and spa focused', 'glow']]],
  ['How much time would you like?', [['About 30 minutes', 'time30'], ['About 45 minutes', 'time45'], ['About 60 minutes', 'time60'], ['A 75–90 minute journey', 'time90']]],
  ['Which enhancement calls to you?', [['Aromatherapy', 'aroma'], ['Sound bowls', 'sound'], ['CBD body care', 'cbd'], ['Keep it beautifully simple', 'simple']]],
  ['Would you enjoy a finishing experience?', [['Facial massage', 'facial'], ['Hand or foot care', 'feet'], ['Makeup artistry', 'makeup'], ['No add-on today', 'none']]],
  ['How should wellness fit your life?', [['A one-time reset', 'once'], ['A regular monthly experience', 'monthly'], ['I’m curious about V.Elevate', 'member'], ['I’m preparing for an occasion', 'occasion']]],
  ['How do you want to feel when you leave?', [['Calm enough to float', 'restore'], ['Loose, mobile, and relieved', 'release'], ['Grounded and centered', 'ground'], ['Radiant and renewed', 'glow']]],
] as const;
const results = {
  restore: { name: 'The Velvet Restoration', copy: 'A deeply calming experience created to quiet the nervous system and soften the whole body.', service: 'IXSRA2CALXNE4TYGLWZXPSJX' },
  release: { name: 'The Royal Release', copy: 'Focused therapeutic care for muscular tension, movement, and the places working hardest.', service: 'NQJ2D262B4FNZILZPIALGNQD' },
  ground: { name: 'The Celestial Grounding', copy: 'Energy awareness, sound, and intentional care to help you feel present in your body.', service: 'PEU265JDBLHWO7DI7RBATYJC' },
  glow: { name: 'The Goddess Glow', copy: 'Restorative beauty care for the face, scalp, hands, or feet that leaves you renewed.', service: 'N22P7RVDZU4YPUD7AIEZV2UC' },
};

Notifications.setNotificationHandler({ handleNotification: async () => ({ shouldShowBanner: true, shouldShowList: true, shouldPlaySound: false, shouldSetBadge: false }) });

export default function App() {
  const [fontsLoaded] = useFonts({ CormorantGaramond_500Medium, CormorantGaramond_600SemiBold, CormorantGaramond_700Bold, Manrope_400Regular, Manrope_500Medium, Manrope_600SemiBold, Manrope_700Bold });
  const [tab, setTab] = useState<Tab>('home');
  const [intake, setIntake] = useState<Intake>({ name: '', email: '', phone: '', goals: '', concerns: '' });
  const [reminders, setReminders] = useState(false);
  useEffect(() => { SecureStore.getItemAsync('velvet-intake').then(value => value && setIntake(JSON.parse(value))).catch(() => undefined); }, []);
  if (!fontsLoaded) return <View style={{ flex: 1, backgroundColor: C.ink }} />;
  const open = (url: string) => Linking.openURL(url).catch(() => Alert.alert('Unable to open link', 'Please try again in a moment.'));
  const toggleReminders = async (enabled: boolean) => {
    if (!enabled) { await Notifications.cancelAllScheduledNotificationsAsync(); setReminders(false); return; }
    const permission = await Notifications.requestPermissionsAsync();
    if (!permission.granted) return Alert.alert('Notifications are off', 'You can allow them later in your phone settings.');
    await Notifications.cancelAllScheduledNotificationsAsync();
    await Notifications.scheduleNotificationAsync({ content: { title: 'Your body deserves care ✨', body: 'Take a breath and reserve your next Simply Velvet experience.' }, trigger: { type: Notifications.SchedulableTriggerInputTypes.WEEKLY, weekday: 2, hour: 10, minute: 0 } });
    setReminders(true);
  };
  return <LinearGradient colors={[C.ink, '#19091f', C.plum]} style={s.app}><StatusBar barStyle="light-content" /><SafeAreaView style={s.safe}>
    <View style={s.header}><View><Text style={s.brand}>Simply Velvet</Text><Text style={s.brandSmall}>SPA • RICHMOND, VIRGINIA</Text></View><Pressable onPress={() => open(SQUARE)} style={s.headerBook}><Text style={s.headerBookText}>BOOK</Text></Pressable></View>
    <ScrollView contentContainerStyle={s.content} showsVerticalScrollIndicator={false}>
      {tab === 'home' && <Home onBook={() => open(SQUARE)} onTab={setTab} open={open} />}
      {tab === 'explore' && <Explore onBook={() => open(SQUARE)} />}
      {tab === 'quiz' && <Quiz onBook={id => open(SQUARE + id)} />}
      {tab === 'velvet' && <MyVelvet intake={intake} setIntake={setIntake} reminders={reminders} toggleReminders={toggleReminders} open={open} />}
    </ScrollView>
    <View style={s.nav}>{([['home', '⌂', 'Home'], ['explore', '✦', 'Explore'], ['quiz', '◇', 'Quiz'], ['velvet', '♕', 'My Velvet']] as const).map(([key, icon, label]) => <Pressable key={key} onPress={() => setTab(key)} style={s.navItem}><Text style={[s.navIcon, tab === key && s.navActive]}>{icon}</Text><Text style={[s.navText, tab === key && s.navActive]}>{label}</Text></Pressable>)}</View>
  </SafeAreaView></LinearGradient>;
}

function Home({ onBook, onTab, open }: { onBook: () => void; onTab: (t: Tab) => void; open: (u: string) => void }) {
  return <><View style={s.hero}><Text style={s.kicker}>IT’S NOT A SERVICE</Text><Text style={s.heroTitle}>It’s an{`\n`}experience.</Text><Text style={s.heroCopy}>Intentional, unrushed massage and elevated wellness designed around what your body needs now.</Text><GoldButton label="Reserve your experience" onPress={onBook} /></View>
    <SectionTitle eyebrow="BEGIN YOUR JOURNEY" title="What is calling you?" /><View style={s.actionGrid}>
      <ActionCard icon="✦" title="Find My Experience" copy="Take the personalized eight-question quiz." onPress={() => onTab('quiz')} />
      <ActionCard icon="☾" title="Explore the Rooms" copy="Step inside every Simply Velvet environment." onPress={() => onTab('explore')} />
      <ActionCard icon="♕" title="V.Elevate" copy="Discover membership, packages, and rewards." onPress={() => onTab('velvet')} />
      <ActionCard icon="♡" title="Gift Wellness" copy="Give someone permission to pause." onPress={() => open(WEBSITE + '/#gift-cards')} />
    </View><SectionTitle eyebrow="FEATURED EXPERIENCE" title="The Queen’s Retreat" />
    <LinearGradient colors={['#522063', '#20102c']} style={s.feature}><Text style={s.featureSymbol}>♕</Text><Text style={s.featureTitle}>Ninety minutes, entirely yours.</Text><Text style={s.body}>A 60-minute massage, Queen’s facial massage, and restorative reflexology brought together as one elevated journey.</Text><View style={s.priceRow}><Text style={s.price}>$220</Text><Text style={s.duration}>90 MINUTES</Text></View><GoldButton label="Reserve the Queen’s Retreat" onPress={() => open(SQUARE + 'Q543VLA7A3U2RGV2S5QR534U')} /></LinearGradient></>;
}

function Explore({ onBook }: { onBook: () => void }) {
  const [selected, setSelected] = useState(0); const room = rooms[selected];
  return <><SectionTitle eyebrow="THE SIMPLY VELVET WORLD" title="Explore the rooms" /><Text style={s.pageIntro}>Each room holds a different part of your journey. Tap a room to enter.</Text>
    <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.roomTabs}>{rooms.map((r, i) => <Pressable key={r.key} onPress={() => setSelected(i)} style={[s.roomPill, i === selected && s.roomPillActive]}><Text style={s.roomPillIcon}>{r.symbol}</Text><Text style={[s.roomPillText, i === selected && s.roomPillTextActive]}>{r.name}</Text></Pressable>)}</ScrollView>
    <LinearGradient colors={[...room.tone]} style={s.roomHero}><Text style={s.roomSymbol}>{room.symbol}</Text><Text style={s.roomName}>The {room.name}</Text><Text style={s.body}>{room.copy}</Text><View style={s.divider} />{room.details.map(x => <View key={x} style={s.detailRow}><Text style={s.check}>✦</Text><Text style={s.detailText}>{x}</Text></View>)}<GoldButton label="View bookable experiences" onPress={onBook} /></LinearGradient>
    <SectionTitle eyebrow="RESERVE YOUR CARE" title="Popular experiences" />{services.map(item => <Pressable key={item.id} onPress={() => Linking.openURL(SQUARE + item.id)} style={s.service}><View><Text style={s.serviceName}>{item.name}</Text><Text style={s.serviceMeta}>{item.meta}</Text></View><Text style={s.serviceArrow}>→</Text></Pressable>)}</>;
}

function Quiz({ onBook }: { onBook: (id: string) => void }) {
  const [step, setStep] = useState(0), [answers, setAnswers] = useState<string[]>([]), [done, setDone] = useState(false);
  const result = useMemo(() => { const score: Record<string, number> = { restore: 0, release: 0, ground: 0, glow: 0 }; answers.forEach(a => { if (a in score) score[a]++; }); return results[Object.entries(score).sort((a, b) => b[1] - a[1])[0][0] as keyof typeof results]; }, [answers]);
  if (done) return <><SectionTitle eyebrow="YOUR PERSONALIZED RESULT" title={result.name} /><LinearGradient colors={['#5c246d', '#1c1027']} style={s.result}><Text style={s.resultMark}>✦</Text><Text style={s.resultTitle}>This journey was chosen for you.</Text><Text style={s.body}>{result.copy}</Text><View style={s.resultLine}><Text style={s.resultLabel}>YOUR NEXT STEP</Text><Text style={s.resultValue}>Reserve the closest available experience, then share your quiz result during intake.</Text></View><GoldButton label="Book this experience" onPress={() => onBook(result.service)} /><Pressable onPress={() => { setAnswers([]); setStep(0); setDone(false); }}><Text style={s.textButton}>Retake the quiz</Text></Pressable></LinearGradient></>;
  const [question, options] = questions[step], selected = answers[step];
  return <><SectionTitle eyebrow={`QUESTION ${step + 1} OF ${questions.length}`} title="Find your experience" /><View style={s.progressTrack}><View style={[s.progress, { width: `${((step + 1) / questions.length) * 100}%` }]} /></View><Text style={s.question}>{question}</Text>{options.map(([label, value]) => <Pressable key={value} onPress={() => { const next = [...answers]; next[step] = value; setAnswers(next); }} style={[s.option, selected === value && s.optionSelected]}><Text style={[s.optionText, selected === value && s.optionTextSelected]}>{label}</Text><Text style={s.optionDot}>{selected === value ? '●' : '○'}</Text></Pressable>)}<View style={s.quizNav}>{step > 0 && <Pressable onPress={() => setStep(step - 1)}><Text style={s.textButton}>← Back</Text></Pressable>}<Pressable disabled={!selected} onPress={() => step === questions.length - 1 ? setDone(true) : setStep(step + 1)} style={[s.continue, !selected && s.disabled]}><Text style={s.continueText}>{step === questions.length - 1 ? 'Reveal my experience' : 'Continue →'}</Text></Pressable></View></>;
}

function MyVelvet({ intake, setIntake, reminders, toggleReminders, open }: { intake: Intake; setIntake: (v: Intake) => void; reminders: boolean; toggleReminders: (v: boolean) => void; open: (u: string) => void }) {
  const save = async () => { await SecureStore.setItemAsync('velvet-intake', JSON.stringify(intake)); Alert.alert('Saved securely', 'Your private intake notes are stored on this device.'); };
  return <><SectionTitle eyebrow="YOUR WELLNESS HOME" title="My Velvet" /><LinearGradient colors={['#5a2167', '#2a1036']} style={s.memberCard}><Text style={s.memberLabel}>V.ELEVATE REWARDS</Text><Text style={s.points}>0</Text><Text style={s.pointsLabel}>VELVET POINTS</Text><Text style={s.memberCopy}>Verified appointments and eligible purchases will build your rewards once your Square customer account is connected.</Text><Pressable onPress={() => open(WEBSITE + '/#memberships')}><Text style={s.memberLink}>Explore membership and packages →</Text></Pressable></LinearGradient>
    <SectionTitle eyebrow="PRIVATE & PERSONAL" title="Your intake" /><Text style={s.pageIntro}>Save the basics now so your arrival can feel calm. Health information stays on this device in this first release.</Text>
    <Field label="Full name" value={intake.name} onChangeText={(v: string) => setIntake({ ...intake, name: v })} /><Field label="Email" value={intake.email} onChangeText={(v: string) => setIntake({ ...intake, email: v })} keyboardType="email-address" /><Field label="Phone" value={intake.phone} onChangeText={(v: string) => setIntake({ ...intake, phone: v })} keyboardType="phone-pad" /><Field label="What would you like help with?" value={intake.goals} onChangeText={(v: string) => setIntake({ ...intake, goals: v })} multiline /><Field label="Anything your therapist should know?" value={intake.concerns} onChangeText={(v: string) => setIntake({ ...intake, concerns: v })} multiline /><GoldButton label="Save my private intake" onPress={save} />
    <View style={s.setting}><View style={{ flex: 1 }}><Text style={s.settingTitle}>Wellness reminders</Text><Text style={s.settingCopy}>A gentle Monday reminder to make space for care.</Text></View><Switch value={reminders} onValueChange={toggleReminders} trackColor={{ false: '#53445a', true: C.gold }} thumbColor={C.white} /></View>
    <View style={s.linkStack}><Pressable onPress={() => open(WEBSITE + '/#gift-cards')} style={s.service}><Text style={s.serviceName}>Gift cards</Text><Text style={s.serviceArrow}>→</Text></Pressable><Pressable onPress={() => open(SQUARE)} style={s.service}><Text style={s.serviceName}>My Square appointments</Text><Text style={s.serviceArrow}>→</Text></Pressable></View></>;
}

function SectionTitle({ eyebrow, title }: { eyebrow: string; title: string }) { return <View style={s.sectionHead}><Text style={s.kicker}>{eyebrow}</Text><Text style={s.sectionTitle}>{title}</Text></View>; }
function GoldButton({ label, onPress }: { label: string; onPress: () => void }) { return <Pressable onPress={onPress} style={({ pressed }) => [s.goldButton, pressed && { opacity: .8 }]}><Text style={s.goldButtonText}>{label}</Text></Pressable>; }
function ActionCard({ icon, title, copy, onPress }: { icon: string; title: string; copy: string; onPress: () => void }) { return <Pressable onPress={onPress} style={s.actionCard}><Text style={s.actionIcon}>{icon}</Text><Text style={s.actionTitle}>{title}</Text><Text style={s.actionCopy}>{copy}</Text><Text style={s.actionArrow}>ENTER →</Text></Pressable>; }
function Field(props: any) { return <View style={s.field}><Text style={s.fieldLabel}>{props.label}</Text><TextInput {...props} placeholderTextColor="#8f8293" style={[s.input, props.multiline && s.inputMulti]} /></View>; }

const s = StyleSheet.create({
  app: { flex: 1 }, safe: { flex: 1, paddingTop: Platform.OS === 'android' ? StatusBar.currentHeight : 0 }, header: { height: 72, paddingHorizontal: 20, borderBottomWidth: 1, borderBottomColor: '#ffffff14', flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, brand: { color: C.pale, fontFamily: 'CormorantGaramond_700Bold', fontSize: 25 }, brandSmall: { color: C.gold, fontFamily: 'Manrope_600SemiBold', fontSize: 8, letterSpacing: 2.2 }, headerBook: { borderColor: C.gold, borderWidth: 1, borderRadius: 30, paddingHorizontal: 17, paddingVertical: 9, shadowColor: C.gold, shadowOpacity: .45, shadowRadius: 10 }, headerBookText: { color: C.gold, fontFamily: 'Manrope_700Bold', fontSize: 10, letterSpacing: 1.5 }, content: { padding: 20, paddingBottom: 44 }, nav: { height: 76, flexDirection: 'row', backgroundColor: '#130918fa', borderTopColor: '#ffffff12', borderTopWidth: 1 }, navItem: { flex: 1, alignItems: 'center', justifyContent: 'center', gap: 3 }, navIcon: { color: '#826f87', fontSize: 20 }, navText: { color: '#826f87', fontFamily: 'Manrope_600SemiBold', fontSize: 9 }, navActive: { color: C.gold },
  hero: { paddingTop: 38, paddingBottom: 28 }, kicker: { color: C.gold, fontFamily: 'Manrope_700Bold', fontSize: 10, letterSpacing: 2.4, marginBottom: 9 }, heroTitle: { color: C.white, fontFamily: 'CormorantGaramond_600SemiBold', fontSize: 58, lineHeight: 52, marginBottom: 17 }, heroCopy: { color: '#d9ccd9', fontFamily: 'Manrope_400Regular', fontSize: 15, lineHeight: 24, marginBottom: 24 }, goldButton: { backgroundColor: C.gold, borderRadius: 4, paddingVertical: 16, paddingHorizontal: 19, alignItems: 'center', shadowColor: C.gold, shadowOpacity: .34, shadowRadius: 14, marginTop: 14 }, goldButtonText: { color: '#241326', fontFamily: 'Manrope_700Bold', fontSize: 12 }, sectionHead: { marginTop: 30, marginBottom: 15 }, sectionTitle: { color: C.white, fontFamily: 'CormorantGaramond_600SemiBold', fontSize: 35, lineHeight: 38 }, pageIntro: { color: '#cbbdcc', fontFamily: 'Manrope_400Regular', fontSize: 14, lineHeight: 22, marginBottom: 17 },
  actionGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 }, actionCard: { width: '48.4%', minHeight: 178, backgroundColor: '#ffffff08', borderWidth: 1, borderColor: '#ffffff13', borderRadius: 12, padding: 17 }, actionIcon: { color: C.gold, fontSize: 25, marginBottom: 12 }, actionTitle: { color: C.white, fontFamily: 'CormorantGaramond_600SemiBold', fontSize: 21, lineHeight: 23 }, actionCopy: { color: '#bcaebf', fontFamily: 'Manrope_400Regular', fontSize: 11, lineHeight: 17, marginTop: 7, flex: 1 }, actionArrow: { color: C.gold, fontFamily: 'Manrope_700Bold', fontSize: 9 }, feature: { borderRadius: 18, padding: 24, borderWidth: 1, borderColor: '#d8ae5835' }, featureSymbol: { color: C.gold, fontSize: 34 }, featureTitle: { color: C.white, fontFamily: 'CormorantGaramond_600SemiBold', fontSize: 31, marginVertical: 7 }, body: { color: '#d7cbd8', fontFamily: 'Manrope_400Regular', fontSize: 14, lineHeight: 22 }, priceRow: { flexDirection: 'row', alignItems: 'baseline', gap: 11, marginTop: 18 }, price: { color: C.gold, fontFamily: 'CormorantGaramond_700Bold', fontSize: 32 }, duration: { color: '#bcaebf', fontFamily: 'Manrope_600SemiBold', fontSize: 10 },
  roomTabs: { gap: 9, paddingBottom: 17 }, roomPill: { width: 135, padding: 13, borderRadius: 10, backgroundColor: '#ffffff08', borderWidth: 1, borderColor: '#ffffff12' }, roomPillActive: { borderColor: C.gold, backgroundColor: '#d8ae5812' }, roomPillIcon: { color: C.gold, fontSize: 18 }, roomPillText: { color: '#b8abbc', fontFamily: 'Manrope_600SemiBold', fontSize: 10, lineHeight: 14, marginTop: 8 }, roomPillTextActive: { color: C.white }, roomHero: { minHeight: 385, borderRadius: 18, padding: 25, justifyContent: 'flex-end', borderColor: '#ffffff1b', borderWidth: 1 }, roomSymbol: { color: C.gold, fontSize: 50, marginBottom: 24 }, roomName: { color: C.white, fontFamily: 'CormorantGaramond_600SemiBold', fontSize: 38, lineHeight: 40, marginBottom: 10 }, divider: { height: 1, backgroundColor: '#ffffff20', marginVertical: 17 }, detailRow: { flexDirection: 'row', gap: 10, marginBottom: 8 }, check: { color: C.gold }, detailText: { color: C.pale, fontFamily: 'Manrope_500Medium', fontSize: 12 }, service: { minHeight: 72, borderBottomWidth: 1, borderBottomColor: '#ffffff18', flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingVertical: 12 }, serviceName: { color: C.white, fontFamily: 'CormorantGaramond_600SemiBold', fontSize: 20 }, serviceMeta: { color: '#a998ac', fontFamily: 'Manrope_500Medium', fontSize: 10, marginTop: 3 }, serviceArrow: { color: C.gold, fontSize: 22 },
  progressTrack: { height: 3, backgroundColor: '#ffffff12', marginBottom: 31 }, progress: { height: 3, backgroundColor: C.gold }, question: { color: C.white, fontFamily: 'CormorantGaramond_600SemiBold', fontSize: 34, lineHeight: 38, marginBottom: 22 }, option: { minHeight: 62, borderWidth: 1, borderColor: '#ffffff18', borderRadius: 10, marginBottom: 11, padding: 17, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', backgroundColor: '#ffffff07' }, optionSelected: { borderColor: C.gold, backgroundColor: '#d8ae5815' }, optionText: { color: '#d3c7d5', fontFamily: 'Manrope_500Medium', fontSize: 13 }, optionTextSelected: { color: C.white }, optionDot: { color: C.gold, fontSize: 18 }, quizNav: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginTop: 15 }, continue: { backgroundColor: C.gold, borderRadius: 4, paddingHorizontal: 19, paddingVertical: 14, marginLeft: 'auto' }, continueText: { color: C.ink, fontFamily: 'Manrope_700Bold', fontSize: 11 }, disabled: { opacity: .3 }, textButton: { color: C.gold, fontFamily: 'Manrope_600SemiBold', fontSize: 12, textAlign: 'center', paddingVertical: 18 }, result: { borderRadius: 18, padding: 26, borderColor: '#d8ae5840', borderWidth: 1 }, resultMark: { color: C.gold, fontSize: 42 }, resultTitle: { color: C.white, fontFamily: 'CormorantGaramond_600SemiBold', fontSize: 28, marginVertical: 10 }, resultLine: { borderTopColor: '#ffffff20', borderTopWidth: 1, marginTop: 22, paddingTop: 18 }, resultLabel: { color: C.gold, fontFamily: 'Manrope_700Bold', fontSize: 9 }, resultValue: { color: C.pale, fontFamily: 'Manrope_400Regular', fontSize: 13, lineHeight: 21, marginTop: 7 },
  memberCard: { borderRadius: 18, padding: 25, borderWidth: 1, borderColor: '#d8ae5840' }, memberLabel: { color: C.gold, fontFamily: 'Manrope_700Bold', fontSize: 10, letterSpacing: 2 }, points: { color: C.white, fontFamily: 'CormorantGaramond_700Bold', fontSize: 64, lineHeight: 67, marginTop: 17 }, pointsLabel: { color: C.gold, fontFamily: 'Manrope_700Bold', fontSize: 9, letterSpacing: 2 }, memberCopy: { color: '#d7cbd8', fontFamily: 'Manrope_400Regular', fontSize: 12, lineHeight: 19, marginTop: 15 }, memberLink: { color: C.gold, fontFamily: 'Manrope_600SemiBold', fontSize: 11, marginTop: 20 }, field: { marginBottom: 14 }, fieldLabel: { color: C.pale, fontFamily: 'Manrope_600SemiBold', fontSize: 11, marginBottom: 7 }, input: { minHeight: 52, borderRadius: 8, borderWidth: 1, borderColor: '#ffffff1b', backgroundColor: '#ffffff08', color: C.white, fontFamily: 'Manrope_400Regular', fontSize: 14, paddingHorizontal: 14 }, inputMulti: { minHeight: 94, paddingTop: 14, textAlignVertical: 'top' }, setting: { marginTop: 27, borderTopWidth: 1, borderBottomWidth: 1, borderColor: '#ffffff18', paddingVertical: 20, flexDirection: 'row', alignItems: 'center', gap: 15 }, settingTitle: { color: C.white, fontFamily: 'CormorantGaramond_600SemiBold', fontSize: 20 }, settingCopy: { color: '#a99bab', fontFamily: 'Manrope_400Regular', fontSize: 10, lineHeight: 16, marginTop: 3 }, linkStack: { marginTop: 18 },
});
